### ISSUE TITLE
不是哥们？#项目文档建议

### ISSUE THREAD

**Issue by AImixBE** [NeoTeak-ORGAN/NeoTeak-Starter#2]
不是哥们
你家就`README.md`是吗
介绍也就这么一点

**Comment by AImixAE** [comment]
不是哥们
我才刚整这个组织啊
你就进来了

**Comment by AImixAE** [comment]
你等等我
我再写点`readme.md`

**Comment by AImixBE** [comment]
好吧好吧

**Comment by AImixBE** [comment]
这么样了
commit: `a082a8b`

**Comment by AImixBE** [comment]
[2b27982](https://github.com/NeoTeak-ORGAN/NeoTeak-Starter/commit/2b27982c37fd7b9dbc51390894d1d77242b4ebd7)

**Comment by AImixAE** [comment]
# 提醒一下
这我是自娱自乐
